### ISSUE TITLE
No rules found from https://dart-lang.github.io/linter/lints/

### ISSUE THREAD

**Issue by ova2** [insideapp-oss/sonar-flutter#107]
I just wanted to create a PR to support FVM (Flutter Version Management https://fvm.app/). We start the analyzing process with `fvm flutter analyze`. But first I wanted to update the rules from https://dart-lang.github.io/linter/lints/ with the existing Groovy script `updateDartAnalyzerRules.groovy`. Saidly, but no rules were found. I have debugged the script and I think the page structure https://dart-lang.github.io/linter/lints/ has been changed and the logic in `def parseRules(url)` should be fixed too. Probably you can parse https://dart.dev/tools/linter-rules. But the parsing of web pages is danger because the pages can be changed in the future.

Anyway, thanks for a great plugin!

Let me know when you fixed this issue (I'm not a Groovy expert). Afterthat, I can create a PR for FVM. I think, we can introduce a new analyzer mode: `sonar.flutter.analyzer.mode=fvm`. What do you think?

**Comment by kuhnroyal** [comment]
I started creating the lints from Dart classes here: https://github.com/insideapp-oss/sonar-flutter/pull/52

But this would have to be done for each new Dart version which has new lints and for each Flutter version. Which in turn needs to migrate the created Sonar rules, deprecated/add new ones etc.
I just don't have the time or willingness to do this.

**Comment by sarn0ld** [comment]
As a workaround you can run analyze yourself and just import the output file:

1. Add `sonar.dart.analysis.reportPath=analyzer.output` to your `sonar-project.properties` file
2. Run `fvm flutter analyze  --no-pub --write=analyzer.output`
3. Run `sonarqube` command
