### ISSUE TITLE
Process 'flutter analyze' timed out after 600000ms.

### ISSUE THREAD

**Issue by salih-g** [insideapp-oss/sonar-flutter#124]
![Error](https://user-images.githubusercontent.com/20362531/172834735-7fb1e85b-bb9d-44b9-ae00-185b0206c596.png)

We are getting this error on our pipeline Can anybody help us?

We are using  0.4.0 version sonar-flutter

**Comment by phuc-tranh-otsv** [comment]
Hi @salih-g sal, 
I think you need install "subosito/flutter-action@v2" before you use sonarqube scanner to run flutter analyze.
