### ISSUE TITLE
The main branch has no lines of code.

### ISSUE THREAD

**Issue by kharisazhar** [insideapp-oss/sonar-flutter#129]
Hi, we already integrate sonarqube, suddenly when we check the sonarqube dashboard shows : The main branch has no lines of code.

<img width="633" alt="Screen Shot 2022-07-12 at 21 27 26" src="https://user-images.githubusercontent.com/30395764/178514338-78593815-17f3-4ea7-9e02-ce0c0413bca4.png">

Here is sonar-scanner log : https://gist.github.com/kharisazhar/582c650cade77f7eaee73f6c7bbe6fe7
sonar-project.properties : https://gist.github.com/kharisazhar/8faced30220a534abb95bbce1bfa943d

My Environment:

`INFO: SonarScanner 4.7.0.2747
INFO: Java 11.0.14.1 Eclipse Adoptium (64-bit)
INFO: Mac OS X 12.4 x86_64
`
SonarQube server 9.5.0.56709
 
` Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (12 days ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2`

I checked the previous bitbucket pipelines : sonar-scanner steps, show successfully in version SonarQube server 8.9.8, but in version 9.5.0.56709, i see dashboard always The main branch has no lines of code.

assumption : 
when you check the log 

`INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
` 

No source files to scan, but when i set `sonar.sources=lib`  to default `sonar.sources=.`, the dashboard show successfully scan android folder, but not lib flutter folder 

Which steps to debug this issue ? 
Thanks

**Comment by sarn0ld** [comment]
The log says nothing about analyzing dart files. Are you sure the sonar flutter plugin is installed and configured?

**Comment by kharisazhar** [comment]
@sarn0ld 

Yes i'm sure flutter plugin is installed and configured well : 

- [ ] Sonarqube 
- [ ] SonarScanner
- [ ] Sonarqube > extensions > plugins > extract sonar-flutter-0.4.0  


```
ijal@ADMINs-MacBook-Pro-7 SonarQube % ls
COPYING			dependency-license.json	logs
bin			elasticsearch		temp
conf			extensions		web
data			lib
```

```
ijal@ADMINs-MacBook-Pro-7 plugins % pwd
/Applications/SonarQube/extensions/plugins

jal@ADMINs-MacBook-Pro-7 plugins % ls
CHANGELOG.md		build-and-deploy.sh	pom.xml
LICENSE.md		dart-lang		screenshots
README.md		mvnw			scripts
README.txt		mvnw.cmd		sonar-flutter-plugin

```


```
ijal@ADMINs-MacBook-Pro-7 SonarScanner % ls
bin	conf	jre	lib

```

**Comment by kharisazhar** [comment]
Any missing steps ?

**Comment by kharisazhar** [comment]
<img width="282" alt="Screen Shot 2022-07-13 at 17 45 48" src="https://user-images.githubusercontent.com/30395764/178716004-14c07087-c7d9-4547-ae23-d76196416b0e.png">
Whops looks like .jar should be install 

and then makesure flutter already install in sonarqube Dashboard : 
<img width="1386" alt="Screen Shot 2022-07-13 at 17 46 41" src="https://user-images.githubusercontent.com/30395764/178716203-4c6c8c41-f938-44b9-a04f-41c126c8423c.png">
