### ISSUE TITLE
Sonar-Flutter plugin not working with SonarQube 9.5

### ISSUE THREAD

**Issue by devs4522** [insideapp-oss/sonar-flutter#131]
SonarQube server is not starting when I am using Sonar-Flutter 0.4.0 version along with SonarQube version 9.5

See web log here:
<img width="1096" alt="Screenshot 2022-07-22 at 12 27 54 PM" src="https://user-images.githubusercontent.com/7301207/180382520-0995d7a0-5280-4cb3-b6e5-f47d2ac176ef.png">

**Comment by Mouette64** [comment]
I have the same issue with Sonar 9.6
