### ISSUE TITLE
ERROR: org.buildobjects.process.StartupException: Could not startup process 'flutter analyze'.

### ISSUE THREAD

**Issue by cuixiaodong** [insideapp-oss/sonar-flutter#162]
I am using Gitlab+Jenkins+Sonar to do quality analysis of Flutter project;
But I encountered the problem of Could not startup process 'flutter analyze';
![image](https://user-images.githubusercontent.com/11581208/232656678-b22bae96-348f-41bf-b475-d1a956e03e2b.png)
![image](https://user-images.githubusercontent.com/11581208/232656814-45890794-4b09-4405-9c20-c24276437e03.png)

Then the previous flutter operations were all executed, and this problem was triggered when the sonar code analysis was executed
![image](https://user-images.githubusercontent.com/11581208/232657055-48816c4d-f441-4fe8-ae17-bf093adde627.png)

**Comment by zippy1978** [comment]
Hi @cuixiaodong ,

"Could not startup process 'flutter analyze'" usually means that the plugin failed to run the "flutter analyze" command
Is flutter install on your Jenkins runner ? Is it on path ?

**Comment by pkneebal** [comment]
@zippy1978
I am having same issue, mine is on path

**Comment by zippy1978** [comment]
Hi @pkneebal,
Which version of the plugin do you use ?
Can you run 'flutter analyze' form your project directory ?

**Comment by soYany** [comment]
哈喽，这个问题怎么解决的？遇到了同样的问题
