### ISSUE TITLE
mutli module analyze report in analyzer.mode=MANUAL has no effect

### ISSUE THREAD

**Issue by jiechic** [insideapp-oss/sonar-flutter#182]
### sonar-project.properties
> sonar.modules=old_utils,okki_flutter,okki_flutter_example,okki_login
>
> old_utils.sonar.projectBaseDir=packages/old-utils
> 
> okki_flutter.sonar.projectBaseDir=packages/okki-flutter
> okki_flutter_example.sonar.projectBaseDir=packages/okki-flutter/example
> 
> okki_login.sonar.projectBaseDir=packages/okki-login
>
> sonar.dart.analyzer.mode=MANUAL
> sonar.dart.analyzer.report.mode=MACHINE
> sonar.dart.analyzer.report.path=analysis-results.txt

### log
```
15:52:27.423 INFO: Indexing files of module 'okki_flutter'
15:52:27.423 INFO:   Base dir: /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter
15:52:27.424 DEBUG:   Source paths: lib, pubspec.yaml
15:52:27.424 DEBUG:   Test paths: test
15:52:27.427 DEBUG: File '/Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/okki_flutter.reflectable.dart' is excluded by the scm ignore settings.
15:52:27.427 DEBUG: File '/Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/gen/res/colors.gen.dart' is excluded by the scm ignore settings.
15:52:27.428 DEBUG: File '/Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/gen/res/assets.gen.dart' is excluded by the scm ignore settings.
15:52:27.429 DEBUG: File '/Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/gen/l10n/okki_flutter_localizations_en.dart' is excluded by the scm ignore settings.
15:52:27.429 DEBUG: File '/Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/gen/l10n/okki_flutter_localizations_zh.dart' is excluded by the scm ignore settings.
15:52:27.430 DEBUG: File '/Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/gen/l10n/okki_flutter_localizations.dart' is excluded by the scm ignore settings.
15:52:27.432 DEBUG: 'packages/okki-flutter/lib/di.dart' indexed with language 'dart'
15:52:27.437 DEBUG: File '/Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/di.module.dart' is excluded by the scm ignore settings.
15:52:27.437 DEBUG: 'packages/okki-flutter/lib/okki_flutter.dart' indexed with language 'dart'




15:52:29.952 DEBUG: Analyzer configured for mode: MANUAL
15:52:29.952 DEBUG: Analyzer configured for output mode: MACHINE
15:52:29.952 INFO: Analysing report from analysis-results.txt
15:52:29.953 INFO: Recording 7 issues
15:52:29.953 DEBUG: Recording issue for /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/okki_flutter.dart
15:52:29.953 WARN: File not included in SonarQube /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/okki_flutter.dart
15:52:29.954 DEBUG: Recording issue for /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/ARepository.dart
15:52:29.955 WARN: File not included in SonarQube /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/ARepository.dart
15:52:29.955 DEBUG: Recording issue for /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/ARepository.dart
15:52:29.955 WARN: File not included in SonarQube /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/ARepository.dart
15:52:29.955 DEBUG: Recording issue for /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/module/whatsapp_business/page/conversation_list_page.dart
15:52:29.955 DEBUG: Recording issue for /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/module/whatsapp_business/widget/audio_message.dart
15:52:29.955 DEBUG: Recording issue for /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/module/whatsapp_business_template/page/template_preview_page.dart
15:52:29.955 DEBUG: Recording issue for /Users/jiechic/WorkSpace/Projects/okmm/packages/okki-flutter/lib/src/utils/vcard_error_utils.dart
15:52:29.955 INFO: Sensor Dart analysis sensor [flutter] (done) | time=7ms
15:52:29.955 INFO: Sensor Flutter unit tests [flutter]
```

<img width="801" alt="image" src="https://github.com/insideapp-oss/sonar-flutter/assets/518977/f88ed879-5523-4927-9f60-f94877e719bb">

### Questions
1、okki-flutter/lib/okki_flutter.dart was indexed with language 'dart' but Analysing result  show 'File not included in SonarQube'
2、In addition to the file does not exist, there are 3 issues, but can not be found on sonar

**Comment by jiechic** [comment]
it's report sonar result on gitlab PR

**Comment by zippy1978** [comment]
Hi @jiechic,

Could you try using `your_module.sonar.sources and `your_module.sonar.tests` instead of `your_module.sonar.projectBaseDir`?
I suspect files are not indexed properly during the analysis.

**Comment by jiechic** [comment]
it's use the same setting with main project setting，
in the pr code ， i can see new code
![image](https://github.com/insideapp-oss/sonar-flutter/assets/518977/ce873fb7-7545-44e3-b1b7-508bb7968bb9)

**Comment by jiechic** [comment]
i test info for setting `your_module.sonar.tests` it's also no effect
![image](https://github.com/insideapp-oss/sonar-flutter/assets/518977/2831724b-f2eb-4e71-97a5-f7055a0af4fa)
![image](https://github.com/insideapp-oss/sonar-flutter/assets/518977/86b27476-1603-437a-942d-1790f1fa9e76)
![image](https://github.com/insideapp-oss/sonar-flutter/assets/518977/8992591f-7576-49a6-ba45-21a219d0522c)

**Comment by jiechic** [comment]
have any update？

**Comment by zippy1978** [comment]
Hi @jiechic,

Could you show the content of your manually generated analysis-results.txt ?

**Comment by Ppito** [comment]
Hello @jiechic,

beware, there is 2 differents things you need to understand.
Result on sonar-scanner and result on Sonarqube.

Unlike all other languages managed by sonar, this plugin does not display your customized results.
You need to configure your own custom rules on `analysis_options.yaml` for sonar-scanner to find your MANUAL report.
But you also need to configure the same rules on your custom Quality Rules on Sonarqube, so that it can analyze the report send by sonar-scanner  and process the results.

At least that's how I understood it.

Personally, I have configured my 72 custom rules in Sonarqube.

But I agree, on one of my PHP project, sonnar-scanner analyzes my project and I can specify a custom report in addition which is well present on Sonarqube.

**Comment by jiechic** [comment]
[analysis-results.txt](https://github.com/insideapp-oss/sonar-flutter/files/13769839/analysis-results.txt)


> Hi @jiechic,
> 
> Could you show the content of your manually generated analysis-results.txt ?

I'm upload a new analysis-results.txt for issue

**Comment by jiechic** [comment]
> Hello @jiechic,
> 
> beware, there is 2 differents things you need to understand. Result on sonar-scanner and result on Sonarqube.
> 
> Unlike all other languages managed by sonar, this plugin does not display your customized results. You need to configure your own custom rules on `analysis_options.yaml` for sonar-scanner to find your MANUAL report. But you also need to configure the same rules on your custom Quality Rules on Sonarqube, so that it can analyze the report send by sonar-scanner and process the results.
> 
> At least that's how I understood it.
> 
> Personally, I have configured my 72 custom rules in Sonarqube.
> 
> But I agree, on one of my PHP project, sonnar-scanner analyzes my project and I can specify a custom report in addition which is well present on Sonarqube.

ths for answer
i have a project is android
it has custom rules use android lints
but sonar havn't these lint ，then it also show lint result on pr result page。

**Comment by Ppito** [comment]
Okay, well, I don't know if that helps.
In my case, I don't you MACHINE report mode, I using the LEGACY mode.
And I run the Analyzer with the following command: `dart analyze > analyzer_report.txt`
I do not analyze with `flutter` because the order of the message in the line result is not the same than dart. And this plugin can only read the dart order in LEGACY  mode and not flutter. (Of course you need to have your own `analysis_options.yaml`, with flutter rules).
[sonar-project.properties](https://github.com/insideapp-oss/sonar-flutter/files/13776936/sonar-project.properties.txt)
This is my sonar configuration, the main application and 4 packages (everything is managed with melos).
