### ISSUE TITLE
Files aren't indexed as dart with SonarQube 10.4.1

### ISSUE THREAD

**Issue by Jannik-dev** [insideapp-oss/sonar-flutter#212]
I am executing the sonar-scanner on `ubuntu:22.04` the SonarQube server is running 10.4.1 and uses the plugin version `0.5.0`.

When running the sonar-scanner, it cannot index the `.dart` files as dart. I downgraded the SonarQube server to the current LTS version (9.9.4) which fixed it.

**Comment by DilanAriza** [comment]
In this issue you can find the solution, there I was able to solve my problem which did not index the files
https://github.com/insideapp-oss/sonar-flutter/issues/203

**Comment by zippy1978** [comment]
Fixed in new release: https://github.com/insideapp-oss/sonar-flutter/releases/tag/0.5.1
