### ISSUE TITLE
[QUESTION] Support dart code linter

### ISSUE THREAD

**Issue by santitigaga** [insideapp-oss/sonar-flutter#216]
[Dart Code linter ](https://dcl.apps.bancolombia.com/)  is a software analytics tool that helps developers analyse and improve software quality. it is based on a fork of Dart Code Metrics. 

Do you think it is possible to add the dart code linter rules in this sonar plugin?

if the project to be scanned does not use it, nothing happens, and if you use DCL it will also report the issues configured in this to

**Comment by zippy1978** [comment]
Hi @santitigaga,

Good idea!
I will have a look at it.

**Comment by santitigaga** [comment]
Hello @zippy1978 Did you get a chance to take a look?
