### ISSUE TITLE
dartanalyzer rules disappeared from SonarQube quality profile

### ISSUE THREAD

**Issue by hassan-saleh-ml** [insideapp-oss/sonar-flutter#223]
Before upgrading to latest version the `dartanalyzer` quality profile had 323 rules, now it only has 53 rules and shows that there are no issues in the code even though I intentionally added dead code and numerous other issues that my `analysis_options.yaml` is reporting.

I tried to create a new quality profile, when I select Dart language I can only choose from those 53 rules and nothing more.

Was this intentional or is it a bug? is there a way to re-activate all the rules and control what is reported using analysis_options?

**Comment by zippy1978** [comment]
Hi @hassan-saleh-ml,

This is strange...
Which version of the plugin and of sonar do you use ?

**Comment by zippy1978** [comment]
Hi @hassan-saleh-ml,

The issue was found and fixed.
It is available in the new release here: https://github.com/insideapp-oss/sonar-flutter/releases/tag/0.5.2
