### ISSUE TITLE
Override analysis_options yaml file with project's 

### ISSUE THREAD

**Issue by jlin95** [insideapp-oss/sonar-flutter#23]
Hi, I'm currently trialling the usage of this plugin to be used in my Flutter project. 

There are some rules I would like to leave out of the analysis, such as:
`dartanalyzer:prefer_double_quotes`, as we are practicing using single quotes instead. 

Is there a way (like pass in a flag) to indicate to use our own project dir's analysis options file? 

Thanks!

**Comment by matpag** [comment]
I have the same problem.
It should be possible to disable some checks and use the project `analysis-options.yaml` file and not the one bundled in the plugin.

**Comment by stephanecodes** [comment]
I created PR #20 one month ago to add this feature. Meanwhile you can switch to my branch.

**Comment by matpag** [comment]
Will try to build your branch as soon as [OpenJDK](https://openjdk.java.net/) site resurrect to download OpenJDK 11 which is required to build the plugin.

**Comment by stephanecodes** [comment]
Here is the one I'm using.

[sonar-flutter-plugin-0.2-SNAPSHOT-PR20.zip](https://github.com/insideapp-oss/sonar-flutter/files/4857695/sonar-flutter-plugin-0.2-SNAPSHOT-PR20.zip)

Follow the update documentation to configure it
https://github.com/stephanecodes/sonar-flutter/tree/feature/allow-existing-analysis-options#use-existing-analysis-options

**Comment by matpag** [comment]
Thank you for the help but for security reasons I can't install a JAR which is not coming from a "trusted" source.
I will wait until OpenJDK is back and will test your changes :)

**Comment by stephanecodes** [comment]
Ok ;)
If by installing you mean on the global SonarQube of your organization, you can try it locally. I'm using SonarQube 7.9.3 LTS
https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.3.zip

**Comment by sebkoller** [comment]
I was surprised that the plugin overrides existing `analysis-options.yaml` rules in the first place.

I guess the expected behavior would be to use the existing rules, and if there are none, fallback to some default rules (preferably pedantic or effective dart).

**Comment by clairtonluz** [comment]
I need this feature. I using **pedantic** rules, but when run `sonar-scan` in my project the `analysis-options.yaml` is overrided. Do you have any predictions about that?

**Comment by stephanecodes** [comment]
You can either use the one I provided a month ago or wait for the maintainer to merge my PR.

**Comment by zippy1978** [comment]
Hi,
I've juste released version 0.3.0 with @stephanecodes PR.
You can use **sonar.dart.analysis.useExistingOptions=true** in your sonar-project.properties files to use your own **analysis-options.yaml**
I'm closing the issue.
