### ISSUE TITLE
When i run sonar-scaneer in my project

### ISSUE THREAD

**Issue by anandat** [insideapp-oss/sonar-flutter#3]
<img width="900" alt="Screenshot 2020-02-13 at 1 47 29 PM" src="https://user-images.githubusercontent.com/19904520/74414411-64ebe280-4e67-11ea-8498-0d4bce22dee0.png">

**Comment by zippy1978** [comment]
Hi @anandat ,

Did you check that "dartanalyzer" command in on your path (to test : type "dartanalyzer -h" in a console) ?

**Comment by anandat** [comment]
Thnx Its works :)

**Comment by Cutux** [comment]
@zippy1978 hi I'm having the same issue, already checked that dartanalyzer is on my path var (in my sonarqube server and in my sonar-scanner host), any suggestion?

Thanks!
