### ISSUE TITLE
Flutter Code Coverage broken even after importing LCOV

### ISSUE THREAD

**Issue by Omniscience619** [insideapp-oss/sonar-flutter#31]
I've been using the following command to generate my code coverage file.

`flutter test --coverage
`

Yet, it has suddenly started throwing this error.

```
ERROR: Error during parsing of the generic coverage report '/tmp/{jenkins-folder}/workspace/{project-name}/{project-name}/coverage/lcov.info'. Look at SonarQube documentation to know the expected XML format.
ERROR: Caused by: Unexpected character 'S' (code 83) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
```
Test coverage was executed successfully and it passes all tests.
Requesting you to look into this.

Thank you for the great work that you've done on the extension!

**Comment by Omniscience619** [comment]
Although I wasn't able to resolve this exact issue, what worked for me was to simply allow this extension to auto-detect coverage files. Will followup if any future issues arise.

**Comment by roiskhoiron** [comment]
Do you have a solution to this problem? What action should be applied to sonar-project.properties?

> I've been using the following command to generate my code coverage file.
> 
> `flutter test --coverage `
> 
> Yet, it has suddenly started throwing this error.
> 
> ```
> ERROR: Error during parsing of the generic coverage report '/tmp/{jenkins-folder}/workspace/{project-name}/{project-name}/coverage/lcov.info'. Look at SonarQube documentation to know the expected XML format.
> ERROR: Caused by: Unexpected character 'S' (code 83) in prolog; expected '<'
>  at [row,col {unknown-source}]: [1,1]
> ```
> 
> Test coverage was executed successfully and it passes all tests. Requesting you to look into this.
> 
> Thank you for the great work that you've done on the extension!
