### ISSUE TITLE
"Best practices" issues break sonar analysis 

### ISSUE THREAD

**Issue by etiennecadicidean** [insideapp-oss/sonar-flutter#4]
This is more of a dart issue but we can add a quick fix

The problem: 
The dartanalyzer cli includes a BestPracticesVerifier producing "hint" outputs. Those outputs are present in the HintCode class but not in the Lint api from where the lint errors are fetched (https://dart-lang.github.io/linter/lints/).

As a consequence, the analysis will break with error "dartanalyzer:ruleXX" does not exist (at least I guess this is the reason)

A quick-fix would be to run the analyzer with the flag --no-hints, to be sure only lint errors get outputed,

But in the meantime we need to find a way to get those hints added to the sonar analysis as well...

**Comment by zippy1978** [comment]
PR https://github.com/insideapp-oss/sonar-flutter/pull/5 merged on develop !
