### ISSUE TITLE
Integrate `dart_code_metrics` package

### ISSUE THREAD

**Issue by ueman** [insideapp-oss/sonar-flutter#53]
Are there any plans to integrate the [dart_code_metrics](https://pub.dev/packages/dart_code_metrics) into this?

This seems like a great addition to the existing support for the linter and analyzer.

**Comment by kuhnroyal** [comment]
I was actually thinking about the same thing a couple days ago.

**Comment by kuhnroyal** [comment]
The manual labor mostly goes into defining the Sqale metrics for each rule. I have written some scripts to automatically generate normal rules in https://github.com/insideapp-oss/sonar-flutter/pull/52 which could be amended with `dart_code_metrics` rules.

**Comment by kuhnroyal** [comment]
https://en.wikipedia.org/wiki/SQALE
This is written by hand here: https://github.com/insideapp-oss/sonar-flutter/blob/master/dart-lang/src/main/resources/fr/insideapp/sonarqube/dart/dartanalyzer/sqale-model.xml and basically defines how much technical debt and there for effort goes into fixing the particular lint warning.
