### ISSUE TITLE
[Enhancement] More detailed explanation in rules description

### ISSUE THREAD

**Issue by xoox** [insideapp-oss/sonar-flutter#57]
Hi, thanks for this valuable plugin. Here is one issue in our daily usage.

The description text in rules is so concise/simple as one sentence. Inexperienced developers have to query dart lint rules website to get reasons for issues and ideas to fix them. It would be much convenient if detailed description was provided in pop-up explanation window, where the actual texts were drew from `description` field of
`dart-lang/src/main/resources/fr/insideapp/sonarqube/dart/dartanalyzer/rules.json`.

Currently the `rules.json` was updated with `scripts/updateDartAnalyzerRules.groovy`, which crawls rules information from dart linter web pages. However there are much machine-friendly data source about dart official lint rules. Here are two of them, which are used to generate https://dart-lang.github.io/linter/lints/ and https://dart.dev/tools/linter-rules web-pages respectively.

* https://github.com/dart-lang/linter/blob/gh-pages/lints/machine/rules.json
* https://github.com/dart-lang/site-www/blob/master/src/_data/linter_rules.json

It will be much helpful if the `description` field of sonar-flutter-plugin's rules are generated through the combination of `description` and `details` from dart official lint rules. `\n\n` can be used to separate `description` and `details` texts as paragraphs in markdown format.

**Comment by kuhnroyal** [comment]
I made some progress on this in https://github.com/insideapp-oss/sonar-flutter/pull/52 which probably can be extended further.
