### ISSUE TITLE
Sonar-flutter plugin not working with Sonarqube 9

### ISSUE THREAD

**Issue by thilinatnt** [insideapp-oss/sonar-flutter#58]
Hi,

I have tried updating to SonarQube Version: 9.0 and seems to be failing when we restart after installing the plugin with following error

![Screenshot 2021-07-08 at 7 26 52 PM](https://user-images.githubusercontent.com/36640320/124914073-816f5880-e022-11eb-87e9-337e3e839979.png)

Any plan to upgrade plugin to support Sonarqube v9 any sooner?
Really appreciate any comment on this!

**Comment by YassineHk** [comment]
+1

**Comment by chtourou-youssef** [comment]
i face same problem here

**Comment by wrughony** [comment]
Some deprecated API have been removed as from SonarQube 9 (+ sonar-plugin-api 9.0.xxx)

https://jira.sonarsource.com/browse/SONAR-14925
https://jira.sonarsource.com/browse/SONAR-14885

https://docs.sonarqube.org/latest/setup/upgrade-notes/

**Comment by zippy1978** [comment]
Thank you @thilinatnt,

@wrughony you are right: it is a deprecated API issue.

Some refactoring is needed to make the plugin work on SonarQube 9.
And also : this will force us to drop SonarQube 6 support.

I will have a look at it.

**Comment by kuhnroyal** [comment]
I started looking at this a couple days ago but didn't get very far yet.

**Comment by ZeroOneTV** [comment]
Hey guys,
I've been trying to use plugin 0.3.2 in sonarqube 9.0 and the service doesn't start.
For those who use sonar in version 6.0, I say you can use plugin 0.3.1 in sonarqube version 8.8, it's working normally

**Comment by kuhnroyal** [comment]
You can build the current develop version. I'll try to create a release soon.

**Comment by kuhnroyal** [comment]
I just released 0.4.0, give it a try. It should fix this.

**Comment by devs4522** [comment]
0.4.0 again failing with same error with SonarQube 9.5
