### ISSUE TITLE
Is the dart report updated?

### ISSUE THREAD

**Issue by magaofei** [insideapp-oss/sonar-flutter#59]
I am using flutter2 and the scan was unsuccessful. According to the report file, I found that the report format has been updated. Is the existing regx unmatched? Has anyone else encountered this problem?

**Comment by kuhnroyal** [comment]
Which commands are you using and which report? Tests or analyzer?

**Comment by magaofei** [comment]
> Which commands are you using and which report? Tests or analyzer?

analyzer

```
error - Target of URI doesn't exist: 'package:xxx/xxx.dart' at xxx/lib/channel/xxx.dart:9:8 - (uri_does_not_exist)
info - The value of the local variable 'currentRouter' isn't used at xxx/lib/channel/xxx.dart:41:12 - (unused_local_variable)
```

**Comment by magaofei** [comment]
Sorry, I was wrong, this is the result of `dart analyze`, not `flutter analyze`

**Comment by kuhnroyal** [comment]
The reports need to be written to file, you need some CLI parameters for that. Not exactly sure which, as the have changed recently. It is possible that the report does no longer work with the plugin.
