### ISSUE TITLE
Java Error when trying to run sonar-scanner

### ISSUE THREAD

**Issue by plateaukao** [insideapp-oss/sonar-flutter#6]
When I tried to run the sonar-scanner, it shows following error message.
Do you have suggestions for which java version should be used?

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/4084738/74825896-a25bde80-5345-11ea-92ff-f9cc9a110112.png">

**Comment by zippy1978** [comment]
Hi @plateaukao,

Could you provide more information ?
- SonarQube version
- Java version
