### ISSUE TITLE
the overage metric does not appear in the report and I have not implemented a single unit test

### ISSUE THREAD

**Issue by amed901107** [insideapp-oss/sonar-flutter#62]
![image_2021-07-30_13-39-37](https://user-images.githubusercontent.com/49206173/127691404-45066157-4383-4a54-8334-3ada20f41a49.png)

**Comment by zippy1978** [comment]
Hi @amed901107,

I'm not sure to get the question: you have tests but they are no reported to sonar and coverage as well ?

**Comment by kuhnroyal** [comment]
@amed901107 Did you solve your problems?

**Comment by amed901107** [comment]
Yes, Thank you
