### ISSUE TITLE
No any Dart/flutter issues found in SQ

### ISSUE THREAD

**Issue by Kaiming-Lee** [insideapp-oss/sonar-flutter#81]
I set up a Flutter plugin in my SonarQube server, but I realized there were no Dart issues were found in the SQ dashboard after scanning my flutter project code using "sonar-scanner". But I can found some JAVA and HTTP issues.

Do I miss something to set up?
 
![image](https://user-images.githubusercontent.com/87961265/133380224-e212a6db-4fb3-44b3-91c2-7bed12acf768.png)

**Comment by kuhnroyal** [comment]
Did you manage to solve it?
