### ISSUE TITLE
Is this plugin a solution for SAST scan in Flutter/Dart

### ISSUE THREAD

**Issue by Kaiming-Lee** [insideapp-oss/sonar-flutter#82]
Hi, 

We are looking for a SAST scanning tool for Flutter/Dart analysis. And found this plugin here, but after integrated this plugin into our SonarQube platform, we realized that there are limited rules that can cover the security-related event. 

It is possible to add more rules into the plugin so that can cover more security-related event? Or does anyone know if there is a SAST tool that can support Flutter/Dart?

![image](https://user-images.githubusercontent.com/87961265/133567891-cb707d1f-bbce-46e7-bd77-57b364d391e1.png)

**Comment by kuhnroyal** [comment]
The plugin currently only uses the rules provided by the Dart and Flutter framework (dartanalyzer) and relies on the the SDKs running the analysis. https://dart-lang.github.io/linter/lints/ pretty much covers the available rules, although not all are in the plugin yet.

We can in theory add custom rules to the plugin but that is currently out of scope, unless you want to pitch in.
