### ISSUE TITLE
I can't start analyse flutter project

### ISSUE THREAD

**Issue by v360-bruno-sato** [insideapp-oss/sonar-flutter#87]
I'm trying to add this plugin into my sonar analyzer, but during my github actions I get this error: 
```
java.io.IOException: org.buildobjects.process.StartupException: Could not startup process 'flutter analyze'.
[...]
... 32 common frames omitted
Caused by: java.io.IOException: Cannot run program "flutter": error=2, No such file or directory
[...]
... 34 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
[...]
... 37 common frames omitted
```
My sonar server was into docker, I've already install flutter into server.

Can anyone help me?

**Comment by kuhnroyal** [comment]
The analyzer is run on the client, not the server. You need to have Flutter available in your Github workflow.
