### ISSUE TITLE
Re-use of existing analyzer report not possible

### ISSUE THREAD

**Issue by kuhnroyal** [insideapp-oss/sonar-flutter#91]
### Discussed in https://github.com/insideapp-oss/sonar-flutter/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **NathanAlcantara** October 22, 2021</sup>
Hello, first thing, i appreciate the effort of doing so amazing plugin, you are awesome!!

I want to know if there is any way to disable the native analysis, because in our company we use the follow command to do the analysis in our CI/CD: `fvm flutter analyze --no-pub --current-package --congratulate --no-fatal-infos --no-fatal-warnings --suppress-analytics`.

Since we use fvm there's no fixed flutter version in the PATH, so always throw a error saying that "flutter command not found".
</div>

**Comment by cantellir** [comment]
Hello guys! There is some updates here? I need to use the sonar.dart.analysis.reportPath key but it seems not working yet.
Thank you!!
